"""
Guide for setting up Telegram bot.
"""

def print_telegram_setup():
    """Print Telegram bot setup instructions."""
    
    print("="*70)
    print("TELEGRAM BOT SETUP GUIDE")
    print("="*70)
    
    print("\n🤖 Setting up your Telegram Bot for Second Brain Agent\n")
    
    print("STEP 1: Create Bot with BotFather")
    print("─"*70)
    print("1. Open Telegram and search for: @BotFather")
    print("2. Start chat and send: /newbot")
    print("3. Follow prompts:")
    print("   - Bot name: Second Brain Agent (or your choice)")
    print("   - Bot username: YourSecondBrainBot (must end with 'bot')")
    print("4. BotFather will give you a TOKEN - copy it!")
    print("   Example: 1234567890:ABCdefGHIjklMNOpqrsTUVwxyz")
    print()
    
    print("STEP 2: Configure Bot")
    print("─"*70)
    print("1. Add token to .env file:")
    print("   TELEGRAM_BOT_TOKEN=your_token_here")
    print()
    print("2. Optional: Set bot commands with BotFather")
    print("   Send to @BotFather: /setcommands")
    print("   Paste these commands:")
    print("   start - Start the bot")
    print("   help - Show help message")
    print()
    
    print("STEP 3: Set Up Webhook (For Production)")
    print("─"*70)
    print("🏠 For Local Development:")
    print("   1. Install ngrok: https://ngrok.com")
    print("   2. Run: ngrok http 8000")
    print("   3. Copy the HTTPS URL (e.g., https://abc123.ngrok.io)")
    print("   4. Set webhook:")
    print("      curl -X POST https://api.telegram.org/bot<TOKEN>/setWebhook \\")
    print("           -d 'url=https://abc123.ngrok.io/api/telegram/webhook'")
    print()
    print("🌐 For Production:")
    print("   Use your actual domain:")
    print("   https://yourdomain.com/api/telegram/webhook")
    print()
    
    print("STEP 4: Test Your Bot")
    print("─"*70)
    print("1. Start your FastAPI backend:")
    print("   python backend/main.py")
    print()
    print("2. Open Telegram and search for your bot")
    print()
    print("3. Send a text message:")
    print("   'Team meeting tomorrow at 10 AM'")
    print()
    print("4. Send a voice message:")
    print("   Record and send")
    print()
    print("5. Bot should respond with:")
    print("   ✅ Note saved with categorization")
    print()
    
    print("="*70)
    print("📱 BOT FEATURES")
    print("="*70)
    print("✅ Accepts text messages")
    print("✅ Accepts voice messages")
    print("✅ Auto-categorizes notes (Work, Personal, etc.)")
    print("✅ Extracts action items")
    print("✅ Sends confirmation with summary")
    print()
    
    print("="*70)
    print("⚠️  TROUBLESHOOTING")
    print("="*70)
    print("❌ Bot not responding?")
    print("   - Check if FastAPI is running")
    print("   - Verify webhook is set correctly")
    print("   - Check logs: python backend/main.py")
    print()
    print("❌ 'Unauthorized' error?")
    print("   - Double-check TELEGRAM_BOT_TOKEN in .env")
    print("   - Make sure token has no extra spaces")
    print()
    print("❌ Webhook not working?")
    print("   - URL must be HTTPS (use ngrok for local)")
    print("   - Check firewall/port 8000 is accessible")
    print()
    
    print("="*70)
    print("🔗 HELPFUL LINKS")
    print("="*70)
    print("   • BotFather: https://t.me/botfather")
    print("   • Telegram Bot API: https://core.telegram.org/bots/api")
    print("   • ngrok: https://ngrok.com")
    print("="*70)


if __name__ == "__main__":
    print_telegram_setup()